from __future__ import annotations

import datetime as dt
import os
import re
import shutil
import zipfile
from pathlib import Path
from typing import Any

from git import Repo
from github import Github

from aras.agents.base import BaseAgent, EventSink
from aras.agents.memory_agent import MemoryAgent
from aras.config import Settings
from aras.utils.fs import safe_write_text


class GitHubAgent(BaseAgent):
    """Create a GitHub repo, commit outputs, push, create release/issue, tag topics."""

    def __init__(self, settings: Settings, memory: MemoryAgent, on_event: EventSink, on_tokens=None) -> None:
        super().__init__(agent_id="github", on_event=on_event, on_tokens=on_tokens)
        self.settings = settings
        self.memory = memory

    async def publish(self, *, topic: str, outputs_root: Path, paper_pdf: Path | None) -> dict[str, Any]:
        """Publish artifacts to GitHub (best-effort)."""
        if not self.settings.github_token:
            self.emit("GITHUB_TOKEN not set; skipping publish")
            return {"url": None, "skipped": True}

        owner = self.settings.github_owner
        gh = Github(self.settings.github_token)
        user = gh.get_user() if not owner else gh.get_organization(owner)
        owner_login = user.login

        slug = _slugify(topic)[:40]
        ts = dt.datetime.utcnow().strftime("%Y%m%d%H%M%S")
        repo_name = f"autonomous-research-{slug}-{ts}"
        self.emit(f"Creating repo {owner_login}/{repo_name}")
        repo = user.create_repo(
            name=repo_name,
            description=f"ARAS research cycle for topic: {topic}",
            private=False,
            has_issues=True,
            has_wiki=False,
            auto_init=True,
        )

        # Prepare local git repo for push.
        local_dir = outputs_root / "_publish_tmp"
        if local_dir.exists():
            shutil.rmtree(local_dir)
        local_dir.mkdir(parents=True, exist_ok=True)
        r = Repo.clone_from(repo.clone_url.replace("https://", f"https://{self.settings.github_token}@"), str(local_dir))

        # Copy artifacts
        for name in ["experiments", "paper", "logs", "IMPROVEMENT_LOG.md", "chroma_db"]:
            src = outputs_root / name
            if not src.exists():
                continue
            dst = local_dir / name
            if src.is_file():
                shutil.copy2(src, dst)
            else:
                if dst.exists():
                    shutil.rmtree(dst)
                shutil.copytree(src, dst)

        # Memory snapshot zip
        snap_dir = local_dir / "memory_snapshot"
        snap_dir.mkdir(parents=True, exist_ok=True)
        zip_path = snap_dir / "chroma_db.zip"
        chroma = outputs_root / "chroma_db"
        if chroma.exists():
            _zip_dir(chroma, zip_path)

        # README
        readme = _readme(topic=topic, repo_full=repo.full_name)
        safe_write_text(local_dir / "README.md", readme)

        r.git.add(A=True)
        r.index.commit("ARAS: publish research artifacts")
        r.remote(name="origin").push()

        url = repo.html_url
        self.emit(f"Pushed repo: {url}")

        # Release with PDF if available
        if paper_pdf and paper_pdf.exists():
            tag = f"paper-{ts}"
            rel = repo.create_git_release(tag=tag, name=f"Paper {ts}", message="Autogenerated research paper")
            rel.upload_asset(str((local_dir / "paper" / "paper.pdf").resolve()), content_type="application/pdf")

        # Issue
        repo.create_issue(title="Research Summary", body=_issue_body(topic=topic))

        # Topics
        try:
            topics = [t for t in (_slugify(topic).split("-")[:8]) if t]
            repo.replace_topics(topics)
        except Exception:
            pass

        return {"url": url, "repo": repo.full_name}


def _zip_dir(src: Path, out_zip: Path) -> None:
    with zipfile.ZipFile(out_zip, "w", compression=zipfile.ZIP_DEFLATED) as z:
        for p in src.rglob("*"):
            if p.is_file():
                z.write(p, p.relative_to(src))


def _slugify(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "topic"


def _readme(*, topic: str, repo_full: str) -> str:
    return f"""# {repo_full}

## Abstract
This repository contains an autonomous research cycle executed by ARAS for the topic: **{topic}**.

## Contents
- `paper/`: LaTeX source and compiled PDF (when available)
- `experiments/`: runnable synthetic experiments + results
- `logs/`: analysis logs and run traces
- `memory_snapshot/`: compressed ChromaDB snapshot for reproducibility
- `IMPROVEMENT_LOG.md`: prompt and pipeline evolution across cycles

## Reproduce
1. Create a virtualenv and install dependencies from `aras/requirements.txt`
2. Run: `py aras/main.py --topic "{topic}"`
"""


def _issue_body(*, topic: str) -> str:
    return f"""Key findings for topic: **{topic}**

- See `paper/paper.pdf` (or `paper/paper.tex`) for the full write-up.
- See `experiments/**/results.json` for metrics and artifact paths.
"""

